const defaultTags: Tag[] = [
    { id: 1, name: '水果', svg: '水果', type: '-' },
    { id: 2, name: '餐饮', svg: '餐饮', type: '-' },
    { id: 3, name: '零食', svg: '零食', type: '-' },
    { id: 4, name: '交通', svg: '交通', type: '-' },
    { id: 5, name: '通讯', svg: '通讯', type: '-' },
    { id: 6, name: '日用品', svg: '日用品', type: '-' },
    { id: 7, name: '服饰', svg: '服饰', type: '-' },
    { id: 8, name: '美容', svg: '美容', type: '-' },
    { id: 9, name: '娱乐', svg: '娱乐', type: '-' },
    { id: 10, name: '健身', svg: '健身', type: '-' },
    { id: 11, name: '医疗', svg: '医疗', type: '-' },
    { id: 12, name: '保险', svg: '保险', type: '-' },
    { id: 13, name: '投资', svg: '投资', type: '-' },
    { id: 14, name: '学习', svg: '学习', type: '-' },
    { id: 15, name: '住房', svg: '住房', type: '-' },
    { id: 16, name: '水电煤', svg: '水电煤', type: '-' },
    { id: 17, name: '维修', svg: '维修', type: '-' },
    { id: 18, name: '停车', svg: '停车', type: '-' },
    { id: 19, name: '加油', svg: '加油', type: '-' },
    { id: 20, name: '发红包', svg: '发红包', type: '-' },
    { id: 21, name: '送礼', svg: '送礼', type: '-' },
    { id: 22, name: '孩子', svg: '孩子', type: '-' },
    { id: 23, name: '宠物', svg: '宠物', type: '-' },
    { id: 24, name: '游戏', svg: '游戏', type: '-' },
    { id: 25, name: '工资', svg: '工资', type: '+' },
    { id: 26, name: '兼职', svg: '兼职', type: '+' },
    { id: 27, name: '生活费', svg: '生活费', type: '+' },
    { id: 28, name: '收红包', svg: '收红包', type: '+' },
    { id: 29, name: '奖金', svg: '奖金', type: '+' },
    { id: 30, name: '投资', svg: '投资', type: '+' },
    { id: 31, name: '报销', svg: '报销', type: '+' },
    { id: 32, name: '借款', svg: '借款', type: '+' },
    { id: 33, name: '退款', svg: '退款', type: '+' },
];
export { defaultTags };